version: "3.8"
services:
  server-app:
    restart: always
    build:
      context: ./server-app
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - ./.env
    volumes:
      - ./server-app:/usr/src/server-app:ro
      - /usr/src/server-app/node_modules
    command: npm run start:dev
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - ${DB_PORT}:${DB_PORT}
