version: "3.8"

services:
  server-app:
    restart: always
    build:
      context: ./server-app
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - ./.env

  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "80:80"
