version: "3.8"

services:
  node-app:
    restart: always
    build:
      context: ./app
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - ./.env
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "80:80"