version: "3.8"

services:
  server-app:
    restart: always
    build:
      context: ./server-app
    env_file:
      - ./.env
    ports:
      - "${PORT}:${PORT}"

  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "80:80"

  web-app:
    restart: always
    build:
      context: ./client-app
      dockerfile: Dockerfile

  app_db:
    image: postgres
    restart: always
    env_file:
      - ./.env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - database_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
  database_data:

networks:
  default:
